### ISSUE TITLE
R - sparse matrices support 

### ISSUE THREAD

**Issue by JackyP** [ModelOriented/DALEX#331]
Hi,

I'm trying to update some code to the latest version, but I am having some difficulty in getting the new functions to work in the same way. Below is a minimal example:

Old code:

```{r}
library(xgboost)
library(Matrix)
library(DALEX)

# Road fatalities data
deaths <- read.csv("https://raw.githubusercontent.com/ActuariesInstitute/YAP-YDAWG-R-Workshop/master/bitre_ardd_fatalities_dec_2018.csv")

# Explain age of the fatality based on speed limit, road user and crash type
sparse_matrix = sparse.model.matrix(Age ~ Speed.Limit + Road.User + Crash.Type, data=deaths)[,-1]

bst <- xgboost(data = sparse_matrix, label = deaths$Age, nrounds=10, objective="reg:linear")

xgb_expl <- explain(model = bst, data = sparse_matrix, y = deaths$Age)

resp <- variable_response(xgb_expl, "Speed.Limit", "pdp")
plot(resp)
```

New code:
```{r}
library(xgboost)
library(Matrix)
library(DALEX)

# Road fatalities data
deaths <- read.csv("https://raw.githubusercontent.com/ActuariesInstitute/YAP-YDAWG-R-Workshop/master/bitre_ardd_fatalities_dec_2018.csv")

model_matrix = sparse.model.matrix(Age ~ Speed.Limit + Road.User + Crash.Type, data=deaths)[,-1]

bst <- xgboost(data = model_matrix, label = deaths$Age, nrounds=10, objective="reg:linear")

xgb_expl <- explain(model = bst, data = model_matrix, y = deaths$Age)

resp <- model_profile(xgb_expl, variables="Speed.Limit")
plot(resp)
```

However I get an error with ``sparse.model.matrix``:
```
Error in as.data.frame.default(x[[i]], optional = TRUE) : 
  cannot coerce class ‘structure("dgCMatrix", package = "Matrix")’ to a data.frame
```

Is there support for models trained on sparse matrix? It saves significant memory compared to using dense matrices for data with many categorical factors and levels.

Additionally, with ``model.matrix`` instead of ``sparse.model.matrix``, it runs, but the new plots have a different look and feel to the old plots. The old plots seem to represent the step changes of a tree based model better than the new plots. 
![pdp_old](https://user-images.githubusercontent.com/16262447/93576855-b00e3b00-f9de-11ea-8a64-3b9b8c8fd546.jpg)
![pdp_new](https://user-images.githubusercontent.com/16262447/93576858-b2709500-f9de-11ea-97e8-08d51c51e000.jpg)

Are there settings that get the old look and feel of the plots? Thanks.

**Comment by maksymiuks** [comment]
Hi,

answering Your question there is a way to run Your model with data as `sparse.model.matrix` object. It can be performed with the usage of DALEXtra package. Because xgboost accepts only matrix data (so one-hot encoded) it could be hard to meaningful explanations for those variables. Therefore `explain_xgboost` function allows the user to pass encode_function, which transforms data.frame objects into objects understandable for the model. In fact `sparse.model.matrix` is such encode function. Below is the code snippet.

```
library(xgboost)
library(Matrix)
library(DALEX)
library(DALEXtra)

# Road fatalities data
deaths <- read.csv("https://raw.githubusercontent.com/ActuariesInstitute/YAP-YDAWG-R-Workshop/master/bitre_ardd_fatalities_dec_2018.csv")

# Explain age of the fatality based on speed limit, road user and crash type
sparse_matrix = sparse.model.matrix(Age ~ Speed.Limit + Road.User + Crash.Type, data=deaths)[,-1]

# AD.1
deaths$Road.User <- as.factor(deaths$Road.User)
deaths$Crash.Type <- as.factor(deaths$Crash.Type)
enc_fun <- function(data) {
  sparse.model.matrix(Age ~ Speed.Limit + Road.User + Crash.Type, data=data)[,-1]
}


bst <- xgboost(data = sparse_matrix, label = deaths$Age, nrounds=10, objective="reg:linear")

# AD.2
xgb_expl <- explain_xgboost(model = bst, data = deaths[,c("Speed.Limit", "Road.User", "Crash.Type", "Age")], y = deaths$Age, encode_function = enc_fun)

resp <- model_profile(xgb_expl, "Speed.Limit", N = 100)

plot(resp)
```
In AD.1 we have to transform character categorical variables into factors. Why? Because methods like PDP randomly chose observation from the data while. We could face an issue when no every level of categorical variable is present in sampled data, in such case if the type is not a factor `sparse.model.matrix` will not create enough columns, and the model will rise and error during the prediction process.

AD.2 is the creation of a simple explainer using `explain_xgboost` function.  The only thing that we should keep in mind is that we need to pass `data` argument that will be understandable for `enc_fun`.

I know that such a solution is not the best one. Conversion from data.frame to sparse.matrix.model with every call of predict function if annoying, but right now I'm not sure if it is even possible to adjust `ingredients` package so it can work sparse.matrix.model straight away. We may need @hbaniecki or @pbiecek input here.

**Comment by pbiecek** [comment]
Hi,
Thank you for an interesting issue.
We try to maintain backward compatibility but this is not always easy.

As Szymon wrote, two problems need to be solved.

First, in newer R versions, the `read_csv` function reads the factors 
as strings, so the variables do not know what the levels are. You have to read data with the `stringsAsFactors = TRUE` option or change the variables to factory later (this is what Simon did).

Secondly, you need to let the explainer know how to process new data, so it is easiest to indicate a manual and predict function that will convert new data into rare data.

Thirdly, the `model_profile` function in order to work faster does not count the PDP profiles at every point, but selects values from the data and calculates PDP values in them. Therefore, these profiles look different because they are calculated for the smaller number of points.
To change this you can set `variable_splits_type = "uniform"`.

Here is the working example

```
library(xgboost)
library(Matrix)
library(DALEX)

# Road fatalities data
deaths <- read.csv("https://raw.githubusercontent.com/ActuariesInstitute/YAP-YDAWG-R-Workshop/master/bitre_ardd_fatalities_dec_2018.csv", 
                   stringsAsFactors = TRUE)

model_matrix = sparse.model.matrix(Age ~ Speed.Limit + Road.User + Crash.Type, data=deaths)

bst <- xgboost(data = model_matrix, label = deaths$Age, nrounds=10, objective="reg:linear")

xgb_expl <- explain(model = bst, data = deaths, y = deaths$Age,
                    predict_function = function(m, x) {
                      sx = sparse.model.matrix(Age ~ Speed.Limit + Road.User + Crash.Type, data=x)
                      predict(m, sx)
                    })

resp <- model_profile(xgb_expl, variables="Speed.Limit", variable_splits_type = "uniform")
plot(resp)
```

or you can specify the grid for calculation directly

```
resp <- model_profile(xgb_expl, variable_splits = list(Speed.Limit = 0:800))
plot(resp)
```

<img width="838" alt="Screenshot 2020-09-19 at 7 14 56 PM" src="https://user-images.githubusercontent.com/4624318/93676058-69871200-faac-11ea-80a3-40e94f12e5c1.png">

**Comment by maksymiuks** [comment]
I think it can be closed
