### ISSUE TITLE
Display transformed variables

### ISSUE THREAD

**Issue by javirandor** [ModelOriented/DALEX#388]
Hello!

I really like your DALEX implementation for Python. I encountered a limitation that would be worth exploring. When representing the explanations, you are restricted to display the values that are inputted to the model. However, these values may have been transformed (e.g. min-max scaling) so it would be really nice to also provide data before the transformation and generate the plots using this values.

Thanks a lot and congratulations!

**Comment by hbaniecki** [comment]
Hi, 
If I understand correctly, this is already possible by using `sklearn.pipeline.Pipeline` from the `scikit-learn` package ( or implementing model pipeline on your own ). We advise using data before transformation in `dalex.Explainer` so that it can generate the plots using these values, while the pipeline model implements imputation/scaling/transformation. See https://dalex.drwhy.ai/python-dalex-titanic.html for example.

**Comment by javirandor** [comment]
Yes. Definitely this is the best way to use the library. However, Pipeline object might not always be available (basically because of lack of knowledge) and it could be useful to handle a simultaneous input that is used as the values to be displayed in the plots.

Something similar to the SHAP library functionality: https://slundberg.github.io/shap/notebooks/Census%20income%20classification%20with%20scikit-learn.html (see cell 4)

**Comment by hbaniecki** [comment]
Have thought about this issue and considering the available key explanations:
- `predict_parts` - possible to implement, convenient to use
- ~`model_parts`~ - no data values in visualizations
- ~`predict_profile` & `model_profile`~ - the explanation knows only the grid of the variable's values (e.g. uniform, quantile), and it would be hard to supply (and substitute) a new grid for each variable
- `model_diagnostics` - possible to implement, but practically requires for the user to supply a whole dataset for visualizations

We focus in `dalex` on providing a convenient explanation object for the user to work with. The `result` attribute is a `pd.DataFrame` that one can freely manipulate to later achieve any given visualization using the `plot` method. 

Here is  an example of displaying values "before the transformation" in `predict_parts`:

<details>
<summary><strong><em>PRELIMINARY CODE</em></strong></summary>

source: https://dalex.drwhy.ai/python-dalex-titanic.html

```python
import dalex as dx

import pandas as pd
import numpy as np

from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

import warnings
warnings.filterwarnings('ignore')

data = dx.datasets.load_titanic()

X = data.drop(columns='survived')
y = data.survived

numerical_features = ['age', 'fare', 'sibsp', 'parch']
numerical_transformer = Pipeline(
    steps=[
        ('imputer', SimpleImputer(strategy='median')),
        ('scaler', StandardScaler())
    ]
)

categorical_features = ['gender', 'class', 'embarked']
categorical_transformer = Pipeline(
    steps=[
        ('imputer', SimpleImputer(strategy='constant', fill_value='missing')),
        ('onehot', OneHotEncoder(handle_unknown='ignore'))
    ]
)

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, numerical_features),
        ('cat', categorical_transformer, categorical_features)
    ]
)

classifier = MLPClassifier(hidden_layer_sizes=(150,100,50), max_iter=500, random_state=0)

clf = Pipeline(steps=[('preprocessor', preprocessor),
                      ('classifier', classifier)])

clf.fit(X, y)
exp = dx.Explainer(clf, X, y)
```

</details>

```python
# default plot
bd = exp.predict_parts(X.iloc[[0]], type='break_down', label="john")
bd.plot()

# access the labels
bd.result.variable[1:8]

# change the labels 
bd.result.variable[1:8] = pd.Series(['b', 'c', 'd', 'e', 'f', 'g', 'h'])
bd.plot()
```

I would say that for now, it would be better for the user to utilize their own code for such customization; instead of adding more parameters and complexity to the `dalex` package. I am still promoting using `Pipeline`s to incorporate transformations into models. 

I am happy to discuss this feature if one decides to contribute code, e.g. PR with adding a new parameter to `BreakDown.plot()` / `Shap.plot()`.
