### ISSUE TITLE
Shapley values or I-breakdown

### ISSUE THREAD

**Issue by neuideas** [ModelOriented/DALEX#434]
Greetings to all the members.

I have started working on Dalex in R language.. I am interested in instance-level explanation but am not sure in which case I need to use the Shapley values and when do I have to consider the iBreakdown approach? 

For example, with Fifa dataset, I want to describe first what are the most important five features for the majority of instances/players. Then, I have to describe the values of these five features that influence the prediction. Just as example, I want to evaluate what are the values of "Age" when the Player is predicted as expensive/worthy and at what values, the Player is predicted as 'not that much expensive'. 

My expected result for 100 players is:  If the age is 20-30, the player is predicted as most worthy, when it is 30-35, second-most worthy and when the values of Age is from 10-20 and 35-40, the players worth is predicted as lowest.

My question, should I use iBreakdown or Shapley values? It seems both work in my case?

**Comment by hbaniecki** [comment]
I will try to explain by thought process as I read your issue:

> For example, with Fifa dataset, I want to describe first what are the most important five features for the majority of instances/players.

This is described by a dataset-level explanation [variable importance](https://ema.drwhy.ai/featureImportance.html) or specifically in the case of FIFA I would recommend using the [`triplot`](https://github.com/ModelOriented/triplot) package (there are a lot of groups of correlated variables).

> Then, I have to describe the values of these five features that influence the prediction. Just as example, I want to evaluate what are the values of "Age" when the Player is predicted as expensive/worthy and at what values, the Player is predicted as 'not that much expensive'.

This is described by a dataset-level explanation [variable dependence](https://ema.drwhy.ai/partialDependenceProfiles.html).

> My expected result for 100 players is:

I believe that you want to use dataset-level explanations to answer such questions, not instance-level.

> My question, should I use iBreakdown or Shapley values? It seems both work in my case?

Shapley values might be better than Break down in the sense that it shows the explanation certainty (boxplots). Nevertheless, these additive explanations do not capture interactions in models; hence, there is a heuristic approach of Interaction + Break down explained in detail in [EMA](https://ema.drwhy.ai/iBreakDown.html) and in the paper [Do Not Trust Additive Explanations](https://arxiv.org/abs/1903.11420).

Actually, the potential answer to your question might be something like this:

```r
library(DALEX)
library(ranger) # random forest model
library(ggplot2)
library(patchwork) # combine plots

df <- fifa[, c(-1, -2, -3, -4)]
model <- ranger(value_eur~., data = df)
explainer <- explain(model,
                     data = df[,-1],
                     y = df$value_eur)

vi <- model_parts(explainer)
most_important_variables <- tail(vi[vi$permutation == 0, ], 6)$variable[-6]

vd <- model_profile(explainer, variables = most_important_variables)

(plot(vi, max_vars=5, subtitle="")) /
  (plot(vd, subtitle="") +
     theme(axis.title.y = element_text(vjust = -20))) +
  plot_layout(heights = c(1, 2))
```

![image](https://user-images.githubusercontent.com/32574004/124570575-5086fc00-de47-11eb-8b87-ff575932bdf9.png)

One can use the [`modelStudio`](https://github.com/ModelOriented/modelStudio) package to automate this process:

```r
library(modelStudio)
modelStudio(explainer, options = ms_options(margin_left = 150))
```

![image](https://user-images.githubusercontent.com/32574004/124572119-b031d700-de48-11eb-98c1-879b2179a610.png)

**Comment by neuideas** [comment]
Thank you Sir for the detailed explanation.

However, if all these things could be achieved with the dataset-level
explanation, what is the purpose of the instance-level explanation then..
My project was to evaluate individually 100 instances of a dataset (e.g.
FIFA) and evaluate first

 (a) what are the four/five features that consistently (or in majority of
the cases) have large impact on the prediction of the instances. (*My
question here:  Does the variable_importance() of dataset level explanation
is the alternative of this evaluating 100 instances and then selecting the
consistent features that impact the prediction of instances???)*

(b) Individually evaluating the values of the 100 instances and checking
which values influence the prediction (My question here: Does the average
predictions of the important features like Age (which you provided above)
is the alternative of evaluating and scanning individual values of 100
observations?)

If the answers to these questions are Yes, then again my point is

" if all these things could be achieved with the dataset-level explanation,
what is the purpose of the instance-level explanation then."

Thank you

**Comment by hbaniecki** [comment]
(a)
> what are the four/five features that consistently (or in majority of the cases) have large impact on the prediction of the instances

To answer this question, I would calculate `variable importance` on the dataset consisting of these 100 instances. Consistently, in the `shap` global variable importance, it is an average of instance importance. [Source](https://github.com/slundberg/shap#tree-ensemble-example-xgboostlightgbmcatboostscikit-learnpyspark-models).

![image](https://user-images.githubusercontent.com/32574004/124599351-dd40b280-de65-11eb-8b8e-63b92c3aa2fc.png) 

> Does the variable_importance() of dataset level explanation is the alternative of this evaluating 100 instances and then selecting the consistent features that impact the prediction of instances???

Not sure, because in this case you would probably want to calculate 100x instance-level explanations, for each choose the 5 most important variables, sum the counts over instances, and finally choose the 5 most impactful variables overall?

(b) Not sure If I can answer this question, but I this picture might be useful. [Source](https://ema.drwhy.ai/partialDependenceProfiles.html).

![image](https://user-images.githubusercontent.com/32574004/124599956-8687a880-de66-11eb-86f6-0de816ce2464.png)

(c) "Instance-level exploration methods help us understand how a model yields a prediction for a particular single observation." 
Citing https://ema.drwhy.ai/InstanceLevelExploration.html. In many situations you need to explain a prediction for regulatory purposes.

**Comment by neuideas** [comment]
Ok, so I think I should should use the instance-level explanation
(preferably Shapley Values) in order to provide findings like: the most
important feature is "Age", which appears important (in top 5 features) in
87% instances, while the other feature comes second, which appears in 70%
instances and so on for other three features.

Similarly, after evaluating 100 instances and the values of important
features, we can say in the majority of cases (e.g. 90%), if the value of
Age is between 25-35, the player has been predicted to be more worthy. Of
course, just to provide an extra analysis, I would also provide the
average of 100 instances via the PDP plots.

Am I wrong? Should (in this case) I go with the instance-level explanation
rather than dataset-level explanation?

Thank you and kind regards

**Comment by hbaniecki** [comment]
> Ok, so I think I should should use the instance-level explanation
(preferably Shapley Values) in order to provide findings like: the most
important feature is "Age", which appears important (in top 5 features) in
87% instances, while the other feature comes second, which appears in 70%
instances and so on for other three features.

Yes, if you are interested in the explanation: "in 87% of instances, Age is in the top5 most important features".

> Similarly, after evaluating 100 instances and the values of important
features, we can say in the majority of cases (e.g. 90%), if the value of
Age is between 25-35, the player has been predicted to be more worthy. Of
course, just to provide an extra analysis, I would also provide the
average of 100 instances via the PDP plots.

Sure, it also depends on the practical meaning of "more worthy".

Your reasoning seems valid to me.

**Comment by neuideas** [comment]
Thank you Sir for all the effort you have made to answer my questions. You
have provided a point by point answer, which I really appreciate.

Kind regards

**Comment by hbaniecki** [comment]
Kind regards
